# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4efb7d57d2ad8050f5678e7198ff6071fb106b12c8e8da9b9855164d68923b3a5489745111cb04e4f2318378094d8b4e7eebde5ea0564ccc7d0061bd9482c5

test:
  secret_key_base: 58e2125defde9aa74e5f2e4d37ff548389ca41b0825ee7f8583d8a5378558a6585bb130037147a2aaa9060aeb8a621eb32bceee236d626f5290c9b6905014401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
